---
stack-compute:
    - ceph::profile::base
    - ceph::profile::client


ceph::fsid: 'f65809d3-7961-4cd7-b731-a9bc94bc6e9c'
ceph::mon_initial_members: 'stack-compute-03,stack-compute-02,stack-compute-01'
ceph::mon_host: '90.147.169.29,90.147.169.28,90.147.169.27'

ceph_osd:
  '/dev/vdb':
    journal: '/data1'
